# Generated by Django 4.2.6 on 2023-10-31 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('fitness_goal', models.CharField(choices=[('SF', 'Stay Fit'), ('LW', 'Lose Weight'), ('BM', 'Build Muscle'), ('KF', 'Keep Fit'), ('IE', 'Improve Endurance')], default='SF', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
