# Generated by Django 4.2.7 on 2023-11-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_age_profile_gender_profile_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
