# Generated by Django 4.2.7 on 2023-11-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_fitness_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(choices=[('SF', 'Stay Fit'), ('LW', 'Lose Weight'), ('BM', 'Build Muscle'), ('KF', 'Keep Fit'), ('IE', 'Improve Endurance')], default='SF', max_length=20),
        ),
    ]
