# Generated by Django 4.2.7 on 2023-11-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('fitness_goal', models.CharField(choices=[('SF', 'Stay Fit'), ('LW', 'Lose Weight'), ('BM', 'Build Muscle'), ('KF', 'Keep Fit'), ('IE', 'Improve Endurance')], default='SF', max_length=20)),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
                ('snacks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
