# Generated by Django 4.2.7 on 2023-11-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='fitness_goal',
            field=models.CharField(choices=[('Stay Fit', 'Stay Fit'), ('Lose Weight', 'Lose Weight'), ('Build Muscle', 'Build Muscle'), ('Keep Fit', 'Keep Fit'), ('Improve Endurance', 'Improve Endurance')], default='SF', max_length=20),
        ),
    ]
