# Generated by Django 4.2.7 on 2023-11-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=150)),
                ('duration', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours')], default='minutes', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('intensity', models.CharField(choices=[('L', 'low'), ('M', 'moderate'), ('V', 'vigorous')], default='M', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=999, null=True)),
                ('equipment_required', models.CharField(blank=True, max_length=50, null=True)),
                ('difficulty_level', models.CharField(choices=[('VH', 'Very Hard'), ('H', 'Hard'), ('M', 'Moderate'), ('E', 'Easy')], default='M', max_length=20)),
                ('repetitions', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
        ),
    ]
