# Generated by Django 4.2.7 on 2023-11-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_exercise_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration_unit',
        ),
    ]
