# Generated by Django 4.2.7 on 2023-11-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_workout_duration_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration_unit',
            field=models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours')], default='minutes', max_length=10),
        ),
    ]
