# Generated by Django 4.2.7 on 2023-11-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_birth_date'),
        ('workouts', '0007_alter_workout_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='users.profile'),
        ),
    ]
