# Generated by Django 4.2.7 on 2023-11-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_workout_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='repetitions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
