# Generated by Django 4.2.7 on 2023-11-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_alter_workout_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='profile',
        ),
        migrations.AddField(
            model_name='workout',
            name='fitness_goal',
            field=models.CharField(choices=[('SF', 'Stay Fit'), ('LW', 'Lose Weight'), ('BM', 'Build Muscle'), ('KF', 'Keep Fit'), ('IE', 'Improve Endurance')], default='SF', max_length=20),
        ),
    ]
